"""Function-mode metadata shared by problem APIs and judge wrapping."""

FUNCTION_SIGNATURES: dict[str, str] = {
    "two-sum": "def two_sum(nums: list[int], target: int) -> list[int]",
    "add-two-numbers": "def addTwoNumbers(l1: ListNode | None, l2: ListNode | None) -> ListNode | None",
    "longest-substring-without-repeating": "def length_of_longest_substring(s: str) -> int",
    "longest-substring-without-repeating-characters": "def length_of_longest_substring(s: str) -> int",
    "valid-parentheses": "def is_valid_parentheses(s: str) -> bool",
    "alien-dictionary": "def alienOrder(words: list[str]) -> str",
    "two-car-parking-lot": "def can_reach(grid: list[list[str]]) -> bool",
    "maximum-subarray": "def max_sub_array(nums: list[int]) -> int",
    "group-anagrams": "def group_anagrams(strs: list[str]) -> list[list[str]]",
    "merge-intervals": "def merge_intervals(intervals: list[list[int]]) -> list[list[int]]",
    "climbing-stairs": "def climb_stairs(n: int) -> int",
    "container-with-most-water": "def max_area(height: list[int]) -> int",
    "logistic-regression-sigmoid": "def predict_probability(weights: list[float], bias: float, features: list[float]) -> float",
    "knn-majority-vote": "def predict_knn(points: list[list[float]], labels: list[str], query: list[float], k: int) -> str",
    "kmeans-one-iteration": "def assign_clusters(points: list[list[float]], centroids: list[list[float]]) -> list[int]",
    "scaled-dot-product-attention": "def attention_row(query: list[float], keys: list[list[float]], values: list[list[float]]) -> list[float]",
    "softmax-cross-entropy": "def cross_entropy_loss(logits: list[float], target: int) -> float",
    "attention-mask-apply": "def masked_softmax(scores: list[float], mask: list[int]) -> list[float]",
    "longest-consecutive-sequence": "def longest_consecutive(nums: list[int]) -> int",
    "move-zeroes": "def move_zeroes(nums: list[int]) -> list[int]",
    "3sum": "def three_sum(nums: list[int]) -> list[list[int]]",
    "trapping-rain-water": "def trap(height: list[int]) -> int",
    "find-all-anagrams-in-a-string": "def find_anagrams(s: str, p: str) -> list[int]",
    "subarray-sum-equals-k": "def subarray_sum(nums: list[int], k: int) -> int",
    "sliding-window-maximum": "def max_sliding_window(nums: list[int], k: int) -> list[int]",
    "minimum-window-substring": "def min_window(s: str, t: str) -> str",
    "rotate-array": "def rotate_array(nums: list[int], k: int) -> list[int]",
    "product-of-array-except-self": "def product_except_self(nums: list[int]) -> list[int]",
    "first-missing-positive": "def first_missing_positive(nums: list[int]) -> int",
    "set-matrix-zeroes": "def set_zeroes(matrix: list[list[int]]) -> list[list[int]]",
    "spiral-matrix": "def spiral_order(matrix: list[list[int]]) -> list[int]",
    "rotate-image": "def rotate_image(matrix: list[list[int]]) -> list[list[int]]",
    "search-a-2d-matrix-ii": "def search_matrix_ii(matrix: list[list[int]], target: int) -> bool",
    "intersection-of-two-linked-lists": "def getIntersectionNode(headA: ListNode | None, headB: ListNode | None) -> ListNode | None",
    "reverse-linked-list": "def reverseList(head: ListNode | None) -> ListNode | None",
    "palindrome-linked-list": "def isPalindrome(head: ListNode | None) -> bool",
    "linked-list-cycle": "def hasCycle(head: ListNode | None) -> bool",
    "linked-list-cycle-ii": "def detectCycle(head: ListNode | None) -> ListNode | None",
    "merge-two-sorted-lists": "def mergeTwoLists(list1: ListNode | None, list2: ListNode | None) -> ListNode | None",
    "remove-nth-node-from-end-of-list": "def removeNthFromEnd(head: ListNode | None, n: int) -> ListNode | None",
    "swap-nodes-in-pairs": "def swapPairs(head: ListNode | None) -> ListNode | None",
    "reverse-nodes-in-k-group": "def reverseKGroup(head: ListNode | None, k: int) -> ListNode | None",
    "copy-list-with-random-pointer": "def copyRandomList(head: Node | None) -> Node | None",
    "sort-list": "def sortList(head: ListNode | None) -> ListNode | None",
    "merge-k-sorted-lists": "def mergeKLists(lists: list[ListNode | None]) -> ListNode | None",
    "lru-cache": "def run_lru_cache(operations: list[str], args: list[list[int]]) -> list[int | None]",
    "binary-tree-inorder-traversal": "def inorderTraversal(root: TreeNode | None) -> list[int]",
    "maximum-depth-of-binary-tree": "def maxDepth(root: TreeNode | None) -> int",
    "invert-binary-tree": "def invertTree(root: TreeNode | None) -> TreeNode | None",
    "symmetric-tree": "def isSymmetric(root: TreeNode | None) -> bool",
    "diameter-of-binary-tree": "def diameterOfBinaryTree(root: TreeNode | None) -> int",
    "binary-tree-level-order-traversal": "def levelOrder(root: TreeNode | None) -> list[list[int]]",
    "convert-sorted-array-to-binary-search-tree": "def sortedArrayToBST(nums: list[int]) -> TreeNode | None",
    "validate-binary-search-tree": "def isValidBST(root: TreeNode | None) -> bool",
    "kth-smallest-element-in-a-bst": "def kthSmallest(root: TreeNode | None, k: int) -> int",
    "binary-tree-right-side-view": "def rightSideView(root: TreeNode | None) -> list[int]",
    "flatten-binary-tree-to-linked-list": "def flatten(root: TreeNode | None) -> None",
    "construct-binary-tree-from-preorder-and-inorder-traversal": "def buildTree(preorder: list[int], inorder: list[int]) -> TreeNode | None",
    "path-sum-iii": "def pathSum(root: TreeNode | None, targetSum: int) -> int",
    "lowest-common-ancestor-of-a-binary-tree": "def lowestCommonAncestor(root: TreeNode | None, p: TreeNode, q: TreeNode) -> TreeNode | None",
    "binary-tree-maximum-path-sum": "def maxPathSum(root: TreeNode | None) -> int",
    "number-of-islands": "def num_islands(grid: list[list[str]]) -> int",
    "rotting-oranges": "def oranges_rotting(grid: list[list[int]]) -> int",
    "course-schedule": "def can_finish(num_courses: int, prerequisites: list[list[int]]) -> bool",
    "implement-trie-prefix-tree": "def run_trie(operations: list[str], args: list[list[str]]) -> list[bool | None]",
    "permutations": "def permute(nums: list[int]) -> list[list[int]]",
    "subsets": "def subsets(nums: list[int]) -> list[list[int]]",
    "letter-combinations-of-a-phone-number": "def letter_combinations(digits: str) -> list[str]",
    "combination-sum": "def combination_sum(candidates: list[int], target: int) -> list[list[int]]",
    "generate-parentheses": "def generate_parenthesis(n: int) -> list[str]",
    "word-search": "def exist(board: list[list[str]], word: str) -> bool",
    "palindrome-partitioning": "def partition_palindromes(s: str) -> list[list[str]]",
    "n-queens": "def solve_n_queens(n: int) -> list[list[str]]",
    "search-insert-position": "def search_insert(nums: list[int], target: int) -> int",
    "search-a-2d-matrix": "def search_matrix(matrix: list[list[int]], target: int) -> bool",
    "find-first-and-last-position-of-element-in-sorted-array": "def search_range(nums: list[int], target: int) -> list[int]",
    "search-in-rotated-sorted-array": "def search_rotated(nums: list[int], target: int) -> int",
    "find-minimum-in-rotated-sorted-array": "def find_min(nums: list[int]) -> int",
    "median-of-two-sorted-arrays": "def find_median_sorted_arrays(nums1: list[int], nums2: list[int]) -> float",
    "min-stack": "def run_min_stack(operations: list[str], args: list[list[int]]) -> list[int | None]",
    "decode-string": "def decode_string(s: str) -> str",
    "daily-temperatures": "def daily_temperatures(temperatures: list[int]) -> list[int]",
    "largest-rectangle-in-histogram": "def largest_rectangle_area(heights: list[int]) -> int",
    "kth-largest-element-in-an-array": "def find_kth_largest(nums: list[int], k: int) -> int",
    "top-k-frequent-elements": "def top_k_frequent(nums: list[int], k: int) -> list[int]",
    "find-median-from-data-stream": "def run_median_finder(operations: list[str], args: list[list[int]]) -> list[float | None]",
    "best-time-to-buy-and-sell-stock": "def max_profit(prices: list[int]) -> int",
    "jump-game": "def can_jump(nums: list[int]) -> bool",
    "jump-game-ii": "def jump(nums: list[int]) -> int",
    "partition-labels": "def partition_labels(s: str) -> list[int]",
    "pascals-triangle": "def generate_pascals_triangle(num_rows: int) -> list[list[int]]",
    "house-robber": "def rob(nums: list[int]) -> int",
    "perfect-squares": "def num_squares(n: int) -> int",
    "coin-change": "def coin_change(coins: list[int], amount: int) -> int",
    "word-break": "def word_break(s: str, word_dict: list[str]) -> bool",
    "longest-increasing-subsequence": "def length_of_lis(nums: list[int]) -> int",
    "maximum-product-subarray": "def max_product(nums: list[int]) -> int",
    "partition-equal-subset-sum": "def can_partition(nums: list[int]) -> bool",
    "longest-valid-parentheses": "def longest_valid_parentheses(s: str) -> int",
    "unique-paths": "def unique_paths(m: int, n: int) -> int",
    "minimum-path-sum": "def min_path_sum(grid: list[list[int]]) -> int",
    "longest-palindromic-substring": "def longest_palindrome(s: str) -> str",
    "longest-common-subsequence": "def longest_common_subsequence(text1: str, text2: str) -> int",
    "edit-distance": "def min_distance(word1: str, word2: str) -> int",
    "single-number": "def single_number(nums: list[int]) -> int",
    "majority-element": "def majority_element(nums: list[int]) -> int",
    "sort-colors": "def sort_colors(nums: list[int]) -> list[int]",
    "next-permutation": "def next_permutation(nums: list[int]) -> list[int]",
    "find-the-duplicate-number": "def find_duplicate(nums: list[int]) -> int",
}
