FROM node:24-slim

RUN apt-get -o Acquire::Retries=5 update && apt-get -o Acquire::Retries=5 install -y --fix-missing --no-install-recommends \
    ca-certificates \
    gcc \
    g++ \
    golang-go \
    python3 \
    python-is-python3 \
    default-jdk-headless \
    && rm -rf /var/lib/apt/lists/*

RUN npm install -g typescript ts-node

WORKDIR /tmp/work

CMD ["sh", "-lc", "sleep infinity"]
