import { localeValue, type Locale } from "../lib/i18n";
import type { SubmissionDetail } from "../lib/schemas";

export type EditableRunCase = {
  id: string;
  input: string;
  expected_output: string;
};

export type RunSnapshot = {
  submissionId: string;
  cases: EditableRunCase[];
};

type DiffSegment = {
  text: string;
  different: boolean;
};

type DiffLine = {
  line: number;
  expected: DiffSegment[];
  actual: DiffSegment[];
  different: boolean;
};

const LABELS = {
  zh: {
    title: "运行结果",
    run: "运行样例",
    reset: "重置",
    add: "添加",
    remove: "删除",
    caseLabel: "用例",
    input: "输入",
    expected: "预期输出",
    actual: "我的输出",
    diff: "差异",
    expectedPending: "运行后由官方解法生成",
    pending: "运行中...",
    notRun: "当前输入尚未运行",
    noOutput: "暂无输出",
    same: "输出一致",
    different: "输出不同",
    runtimeError: "运行错误",
  },
  en: {
    title: "Run Result",
    run: "Run cases",
    reset: "Reset",
    add: "Add",
    remove: "Remove",
    caseLabel: "Case",
    input: "Input",
    expected: "Expected",
    actual: "Your output",
    diff: "Diff",
    expectedPending: "Generated by the official solution after running",
    pending: "Running...",
    notRun: "Current input has not been run",
    noOutput: "No output yet",
    same: "Output matches",
    different: "Output differs",
    runtimeError: "Runtime error",
  },
} as const;

type RunResultLabels = Record<keyof (typeof LABELS)["zh"], string>;
const LABEL_LOOKUP: Partial<Record<Locale, RunResultLabels>> & Record<"zh", RunResultLabels> = LABELS;

export function RunResultPanel({
  locale,
  cases,
  activeIndex,
  submission,
  snapshot,
  canRun,
  onActiveIndex,
  onChangeInput,
  onAddCase,
  onRemoveCase,
  onResetCases,
  onRun,
}: {
  locale: Locale;
  cases: EditableRunCase[];
  activeIndex: number;
  submission: SubmissionDetail | null;
  snapshot: RunSnapshot | null;
  canRun: boolean;
  onActiveIndex: (index: number) => void;
  onChangeInput: (index: number, value: string) => void;
  onAddCase: () => void;
  onRemoveCase: (index: number) => void;
  onResetCases: () => void;
  onRun: () => void;
}) {
  const labels = localeValue(locale, LABEL_LOOKUP);
  const safeCases = cases.length ? cases : [{ id: "case-1", input: "", expected_output: "" }];
  const currentIndex = Math.min(activeIndex, safeCases.length - 1);
  const currentCase = safeCases[currentIndex];
  const visibleResults = (submission?.testcase_results ?? []).filter((item) => !item.is_hidden);
  const result = visibleResults[currentIndex];
  const snapshotCase = snapshot?.cases[currentIndex];
  const resultApplies = Boolean(
    result &&
    submission &&
    snapshot?.submissionId === submission.id &&
    snapshotCase &&
    snapshotCase.input === currentCase.input,
  );
  const running = submission?.status === "pending" || submission?.status === "judging" || snapshot?.submissionId === "";
  const status = resultApplies ? result?.status : running ? "pending" : "idle";
  const actualOutput = resultApplies ? result?.actual_output ?? "" : "";
  const expectedOutput = resultApplies ? result?.expected_output ?? "" : currentCase.expected_output;
  const hasMismatch = resultApplies && result?.status !== "ac";
  const hasError = resultApplies && ["ce", "re", "tle", "mle", "se"].includes(result?.status ?? "");

  return (
    <section className="run-result-panel" aria-label={labels.title}>
      <div className="run-result-header">
        <h2>{labels.title}</h2>
        <div className="run-result-actions">
          <button type="button" className="icon-button reset-template-button tip" data-tip={labels.reset} aria-label={labels.reset} onClick={onResetCases}>
            <ResetIcon />
          </button>
          <button type="button" className="icon-button tip" data-tip={labels.add} onClick={onAddCase}>+</button>
          <button type="button" className="icon-button primary tip" data-tip={labels.run} disabled={!canRun} onClick={onRun}>▶</button>
        </div>
      </div>

      <div className="run-case-tabs" role="tablist" aria-label={labels.caseLabel}>
        {safeCases.map((item, index) => (
          <div
            key={item.id}
            className={currentIndex === index ? "run-case-tab active" : "run-case-tab"}
          >
            <button
              type="button"
              className="run-case-tab-button"
              role="tab"
              aria-selected={currentIndex === index}
              onClick={() => onActiveIndex(index)}
            >
              {labels.caseLabel} {index + 1}
            </button>
            {safeCases.length > 1 ? (
              <button
                type="button"
                className="run-case-tab-remove tip"
                data-tip={labels.remove}
                aria-label={`${labels.remove} ${labels.caseLabel} ${index + 1}`}
                onClick={() => onRemoveCase(index)}
              >
                ×
              </button>
            ) : null}
          </div>
        ))}
      </div>

      <div className="run-result-body">
        <div className="run-input-column">
          <label>
            <span>{labels.input}</span>
            <textarea value={currentCase.input} spellCheck={false} onChange={(event) => onChangeInput(currentIndex, event.target.value)} />
          </label>
          <OutputBox title={labels.expected} value={expectedOutput} placeholder={running ? labels.pending : labels.expectedPending} />
        </div>

        <div className="run-output-column">
          <div className={`run-status ${status ?? "idle"}`}>
            <strong>{statusLabel(status, labels)}</strong>
            {resultApplies && result?.execute_time != null ? <span>{result.execute_time}ms</span> : null}
          </div>
          <OutputBox title={labels.actual} value={actualOutput} placeholder={running ? labels.pending : resultApplies ? labels.noOutput : labels.notRun} />
          <div className="run-diff-card">
            <div className="run-diff-heading">
              <span>{labels.diff}</span>
              <strong className={hasMismatch ? "mismatch" : "match"}>{hasMismatch ? labels.different : labels.same}</strong>
            </div>
            {hasMismatch && !hasError ? <DiffView expected={expectedOutput} actual={actualOutput} /> : null}
            {hasError ? <pre>{result?.actual_output || submission?.error_message || labels.runtimeError}</pre> : null}
            {!hasMismatch && !hasError ? <pre>{labels.same}</pre> : null}
          </div>
        </div>
      </div>
    </section>
  );
}

function ResetIcon() {
  return (
    <svg className="reset-template-icon" viewBox="0 0 24 24" aria-hidden="true">
      <path d="M5.4 9.2a7.2 7.2 0 1 1 1.2 6.9" />
      <path d="M5.4 9.2H2.2V6" />
    </svg>
  );
}

function OutputBox({ title, value, placeholder }: { title: string; value: string; placeholder: string }) {
  return (
    <div className="run-output-card">
      <span>{title}</span>
      <pre>{value || placeholder}</pre>
    </div>
  );
}

function DiffView({ expected, actual }: { expected: string; actual: string }) {
  const lines = buildDiffLines(expected, actual);
  return (
    <div className="run-diff-lines">
      {lines.map((line) => (
        <div className={line.different ? "run-diff-line changed" : "run-diff-line"} key={line.line}>
          <span>{line.line}</span>
          <code>
            <b>-</b>{renderSegments(line.expected)}
            {"\n"}
            <b>+</b>{renderSegments(line.actual)}
          </code>
        </div>
      ))}
    </div>
  );
}

function renderSegments(segments: DiffSegment[]) {
  return segments.map((segment, index) => (
    <mark className={segment.different ? "changed" : ""} key={`${segment.text}-${index}`}>
      {segment.text || " "}
    </mark>
  ));
}

function statusLabel(status: string | undefined, labels: RunResultLabels) {
  if (status === "pending" || status === "judging") return labels.pending;
  if (status === "ac") return labels.same;
  if (status && status !== "idle") return labels.different;
  return labels.notRun;
}

export function buildDiffLines(expected: string, actual: string): DiffLine[] {
  const expectedLines = splitComparableLines(expected);
  const actualLines = splitComparableLines(actual);
  const length = Math.max(expectedLines.length, actualLines.length, 1);
  return Array.from({ length }, (_, index) => {
    const expectedLine = expectedLines[index] ?? "";
    const actualLine = actualLines[index] ?? "";
    return {
      line: index + 1,
      expected: diffSegments(expectedLine, actualLine),
      actual: diffSegments(actualLine, expectedLine),
      different: expectedLine !== actualLine,
    };
  });
}

function splitComparableLines(value: string) {
  const normalized = value.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
  return normalized.length ? normalized.split("\n") : [""];
}

function diffSegments(value: string, other: string): DiffSegment[] {
  if (value === other) return [{ text: value, different: false }];
  let prefix = 0;
  while (prefix < value.length && prefix < other.length && value[prefix] === other[prefix]) prefix += 1;
  let suffix = 0;
  while (
    suffix < value.length - prefix &&
    suffix < other.length - prefix &&
    value[value.length - 1 - suffix] === other[other.length - 1 - suffix]
  ) {
    suffix += 1;
  }
  const segments: DiffSegment[] = [];
  if (prefix > 0) segments.push({ text: value.slice(0, prefix), different: false });
  segments.push({ text: value.slice(prefix, value.length - suffix), different: true });
  if (suffix > 0) segments.push({ text: value.slice(value.length - suffix), different: false });
  return segments;
}
