"""Seed metadata for the LeetCode Hot 100-style practice catalog.

Statements are intentionally short FastOJ originals. Several linked-list and
tree problems use JSON arrays as their ACM input representation so the judge can
stay language-agnostic.
"""

from backend.models import Difficulty

HOT100_LEGACY_SLUG_ALIASES = {
    "longest-substring-without-repeating-characters": [
        "longest-substring-without-repeating",
    ],
}

HOT100_CANONICAL_SLUGS = [
    "two-sum",
    "group-anagrams",
    "longest-consecutive-sequence",
    "move-zeroes",
    "container-with-most-water",
    "3sum",
    "trapping-rain-water",
    "longest-substring-without-repeating-characters",
    "find-all-anagrams-in-a-string",
    "subarray-sum-equals-k",
    "sliding-window-maximum",
    "minimum-window-substring",
    "maximum-subarray",
    "merge-intervals",
    "rotate-array",
    "product-of-array-except-self",
    "first-missing-positive",
    "set-matrix-zeroes",
    "spiral-matrix",
    "rotate-image",
    "search-a-2d-matrix-ii",
    "intersection-of-two-linked-lists",
    "reverse-linked-list",
    "palindrome-linked-list",
    "linked-list-cycle",
    "linked-list-cycle-ii",
    "merge-two-sorted-lists",
    "add-two-numbers",
    "remove-nth-node-from-end-of-list",
    "swap-nodes-in-pairs",
    "reverse-nodes-in-k-group",
    "copy-list-with-random-pointer",
    "sort-list",
    "merge-k-sorted-lists",
    "lru-cache",
    "binary-tree-inorder-traversal",
    "maximum-depth-of-binary-tree",
    "invert-binary-tree",
    "symmetric-tree",
    "diameter-of-binary-tree",
    "binary-tree-level-order-traversal",
    "convert-sorted-array-to-binary-search-tree",
    "validate-binary-search-tree",
    "kth-smallest-element-in-a-bst",
    "binary-tree-right-side-view",
    "flatten-binary-tree-to-linked-list",
    "construct-binary-tree-from-preorder-and-inorder-traversal",
    "path-sum-iii",
    "lowest-common-ancestor-of-a-binary-tree",
    "binary-tree-maximum-path-sum",
    "number-of-islands",
    "rotting-oranges",
    "course-schedule",
    "implement-trie-prefix-tree",
    "permutations",
    "subsets",
    "letter-combinations-of-a-phone-number",
    "combination-sum",
    "generate-parentheses",
    "word-search",
    "palindrome-partitioning",
    "n-queens",
    "search-insert-position",
    "search-a-2d-matrix",
    "find-first-and-last-position-of-element-in-sorted-array",
    "search-in-rotated-sorted-array",
    "find-minimum-in-rotated-sorted-array",
    "median-of-two-sorted-arrays",
    "valid-parentheses",
    "min-stack",
    "decode-string",
    "daily-temperatures",
    "largest-rectangle-in-histogram",
    "kth-largest-element-in-an-array",
    "top-k-frequent-elements",
    "find-median-from-data-stream",
    "best-time-to-buy-and-sell-stock",
    "jump-game",
    "jump-game-ii",
    "partition-labels",
    "climbing-stairs",
    "pascals-triangle",
    "house-robber",
    "perfect-squares",
    "coin-change",
    "word-break",
    "longest-increasing-subsequence",
    "maximum-product-subarray",
    "partition-equal-subset-sum",
    "longest-valid-parentheses",
    "unique-paths",
    "minimum-path-sum",
    "longest-palindromic-substring",
    "longest-common-subsequence",
    "edit-distance",
    "single-number",
    "majority-element",
    "sort-colors",
    "next-permutation",
    "find-the-duplicate-number",
]

_DIFFICULTIES = {
    "easy": Difficulty.EASY,
    "medium": Difficulty.MEDIUM,
    "hard": Difficulty.HARD,
}


def _case(input_data: str, output: str, score: int = 45) -> dict:
    return {
        "input": input_data,
        "output": output,
        "is_sample": False,
        "is_hidden": True,
        "score": score,
    }


def _problem(
    title: str,
    slug: str,
    difficulty: str,
    tags: list[str],
    description: str,
    hint: str,
    cases: list[tuple[str, str]],
    *,
    time_limit: int = 1000,
) -> dict:
    testcases = [_case(input_data, output) for input_data, output in cases]
    if testcases:
        testcases[0]["is_sample"] = True
        testcases[0]["is_hidden"] = False
        testcases[0]["score"] = 10
    return {
        "problem": {
            "title": title,
            "slug": slug,
            "description": description,
            "difficulty": _DIFFICULTIES[difficulty],
            "time_limit": time_limit,
            "memory_limit": 256,
            "tags": ["Hot 100", *tags],
            "hint": hint,
            "source": "Hot 100 practice",
            "mode": "acm",
        },
        "testcases": testcases,
    }


HOT100_PROBLEMS_DATA = [
    _problem(
        "Longest Consecutive Sequence",
        "longest-consecutive-sequence",
        "medium",
        ["Array", "Hash Table"],
        "Given an unsorted integer array, return the length of the longest run of consecutive values.",
        "Only start counting from a value that has no predecessor in the set.",
        [("[100,4,200,1,3,2]", "4"), ("[0,3,7,2,5,8,4,6,0,1]", "9"), ("[1,2,0,1]", "3")],
    ),
    _problem(
        "Move Zeroes",
        "move-zeroes",
        "easy",
        ["Array", "Two Pointers"],
        "Move every zero to the end while keeping non-zero values in their original order.",
        "Write non-zero values forward, then fill the suffix with zeroes.",
        [("[0,1,0,3,12]", "[1,3,12,0,0]"), ("[0]", "[0]"), ("[4,0,5,0,0,3]", "[4,5,3,0,0,0]")],
    ),
    _problem(
        "3Sum",
        "3sum",
        "medium",
        ["Array", "Two Pointers", "Sorting"],
        "Return all unique triples whose values sum to zero. Sort each triple and the outer list.",
        "Sort first, then fix one value and scan the remaining range with two pointers.",
        [
            ("[-1,0,1,2,-1,-4]", "[[-1,-1,2],[-1,0,1]]"),
            ("[0,1,1]", "[]"),
            ("[0,0,0]", "[[0,0,0]]"),
        ],
        time_limit=2000,
    ),
    _problem(
        "Trapping Rain Water",
        "trapping-rain-water",
        "hard",
        ["Array", "Two Pointers", "Dynamic Programming", "Stack"],
        "Given bar heights, compute how much water can be trapped after raining.",
        "Track the best wall seen from both sides and move the lower side inward.",
        [("[0,1,0,2,1,0,1,3,2,1,2,1]", "6"), ("[4,2,0,3,2,5]", "9"), ("[1,2,3]", "0")],
    ),
    _problem(
        "Find All Anagrams in a String",
        "find-all-anagrams-in-a-string",
        "medium",
        ["Hash Table", "String", "Sliding Window"],
        "Return all start indexes where a substring of s is an anagram of p.",
        "Maintain character counts for a fixed-size window.",
        [("cbaebabacd\nabc", "[0,6]"), ("abab\nab", "[0,1,2]"), ("baa\naa", "[1]")],
    ),
    _problem(
        "Subarray Sum Equals K",
        "subarray-sum-equals-k",
        "medium",
        ["Array", "Hash Table", "Prefix Sum"],
        "Count contiguous subarrays whose sum equals k.",
        "If prefix[j] - prefix[i] is k, then a previous prefix of prefix[j] - k can pair with j.",
        [("[1,1,1]\n2", "2"), ("[1,2,3]\n3", "2"), ("[-1,-1,1]\n0", "1")],
    ),
    _problem(
        "Sliding Window Maximum",
        "sliding-window-maximum",
        "hard",
        ["Array", "Queue", "Sliding Window", "Monotonic Queue"],
        "For each window of size k, return the maximum value.",
        "Keep candidate indexes in decreasing value order.",
        [
            ("[1,3,-1,-3,5,3,6,7]\n3", "[3,3,5,5,6,7]"),
            ("[1]\n1", "[1]"),
            ("[9,10,9,-7,-4,-8,2,-6]\n5", "[10,10,9,2]"),
        ],
    ),
    _problem(
        "Minimum Window Substring",
        "minimum-window-substring",
        "hard",
        ["String", "Hash Table", "Sliding Window"],
        "Return the shortest substring of s containing every character required by t, including duplicates.",
        "Expand until all required counts are covered, then shrink from the left.",
        [("ADOBECODEBANC\nABC", "BANC"), ("a\na", "a"), ("a\naa", "")],
        time_limit=2000,
    ),
    _problem(
        "Rotate Array",
        "rotate-array",
        "medium",
        ["Array", "Math", "Two Pointers"],
        "Rotate the array to the right by k steps and return the resulting array.",
        "Reduce k by the array length; a reversal or slicing view solves the rotation.",
        [("[1,2,3,4,5,6,7]\n3", "[5,6,7,1,2,3,4]"), ("[-1,-100,3,99]\n2", "[3,99,-1,-100]"), ("[1,2]\n3", "[2,1]")],
    ),
    _problem(
        "Product of Array Except Self",
        "product-of-array-except-self",
        "medium",
        ["Array", "Prefix Product"],
        "For every index, return the product of all other values without using division.",
        "Combine prefix products from the left with suffix products from the right.",
        [("[1,2,3,4]", "[24,12,8,6]"), ("[-1,1,0,-3,3]", "[0,0,9,0,0]"), ("[2,3]", "[3,2]")],
    ),
    _problem(
        "First Missing Positive",
        "first-missing-positive",
        "hard",
        ["Array", "Hash Table"],
        "Return the smallest positive integer that does not appear in the array.",
        "Place value x at index x - 1 whenever possible.",
        [("[1,2,0]", "3"), ("[3,4,-1,1]", "2"), ("[7,8,9,11,12]", "1")],
    ),
    _problem(
        "Set Matrix Zeroes",
        "set-matrix-zeroes",
        "medium",
        ["Array", "Matrix"],
        "If a matrix cell is zero, set its entire row and column to zero.",
        "Record which rows and columns contain zero before rewriting the matrix.",
        [
            ("[[1,1,1],[1,0,1],[1,1,1]]", "[[1,0,1],[0,0,0],[1,0,1]]"),
            ("[[0,1,2,0],[3,4,5,2],[1,3,1,5]]", "[[0,0,0,0],[0,4,5,0],[0,3,1,0]]"),
            ("[[1]]", "[[1]]"),
        ],
    ),
    _problem(
        "Spiral Matrix",
        "spiral-matrix",
        "medium",
        ["Array", "Matrix", "Simulation"],
        "Return all matrix values in clockwise spiral order.",
        "Walk the current top row, right column, bottom row, and left column, then shrink boundaries.",
        [
            ("[[1,2,3],[4,5,6],[7,8,9]]", "[1,2,3,6,9,8,7,4,5]"),
            ("[[1,2,3,4],[5,6,7,8],[9,10,11,12]]", "[1,2,3,4,8,12,11,10,9,5,6,7]"),
            ("[[1]]", "[1]"),
        ],
    ),
    _problem(
        "Rotate Image",
        "rotate-image",
        "medium",
        ["Array", "Matrix"],
        "Rotate an n by n matrix 90 degrees clockwise and return the result.",
        "Transpose the matrix, then reverse each row.",
        [
            ("[[1,2,3],[4,5,6],[7,8,9]]", "[[7,4,1],[8,5,2],[9,6,3]]"),
            ("[[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]]", "[[15,13,2,5],[14,3,4,1],[12,6,8,9],[16,7,10,11]]"),
            ("[[1]]", "[[1]]"),
        ],
    ),
    _problem(
        "Search a 2D Matrix II",
        "search-a-2d-matrix-ii",
        "medium",
        ["Array", "Binary Search", "Matrix"],
        "A matrix is sorted left-to-right in rows and top-to-bottom in columns. Return whether target exists.",
        "Start at the top-right corner and discard one row or one column at each step.",
        [
            ("[[1,4,7,11,15],[2,5,8,12,19],[3,6,9,16,22],[10,13,14,17,24],[18,21,23,26,30]]\n5", "true"),
            ("[[1,4,7,11,15],[2,5,8,12,19],[3,6,9,16,22],[10,13,14,17,24],[18,21,23,26,30]]\n20", "false"),
            ("[[-5]]\n-5", "true"),
        ],
    ),
    _problem(
        "Intersection of Two Linked Lists",
        "intersection-of-two-linked-lists",
        "easy",
        ["Linked List", "Two Pointers"],
        "The function receives headA and headB. Samples use arrays to build lists with a shared suffix; return the intersecting node value, or null.",
        "Use two pointers that traverse A+B and B+A until they meet.",
        [("[4,1,8,4,5]\n[5,6,1,8,4,5]", "8"), ("[1,9,1,2,4]\n[3,2,4]", "2"), ("[2,6,4]\n[1,5]", "null")],
    ),
    _problem(
        "Reverse Linked List",
        "reverse-linked-list",
        "easy",
        ["Linked List", "Recursion"],
        "The function receives the list head. Reverse node pointers and return the new head; samples display node values as arrays.",
        "Maintain prev and current pointers while rewiring next.",
        [("[1,2,3,4,5]", "[5,4,3,2,1]"), ("[1,2]", "[2,1]"), ("[]", "[]")],
    ),
    _problem(
        "Palindrome Linked List",
        "palindrome-linked-list",
        "easy",
        ["Linked List", "Two Pointers", "Stack"],
        "The function receives the list head. Return whether its node values form a palindrome.",
        "Compare mirrored positions or reverse the second half.",
        [("[1,2,2,1]", "true"), ("[1,2]", "false"), ("[1]", "true")],
    ),
    _problem(
        "Linked List Cycle",
        "linked-list-cycle",
        "easy",
        ["Linked List", "Two Pointers"],
        "The function receives a head node. Tests build the list from values plus a tail-link index, then expect whether a cycle exists.",
        "Use slow and fast pointers; a meeting point means there is a cycle.",
        [("[3,2,0,-4]\n1", "true"), ("[1,2]\n0", "true"), ("[1]\n-1", "false")],
    ),
    _problem(
        "Linked List Cycle II",
        "linked-list-cycle-ii",
        "medium",
        ["Linked List", "Two Pointers"],
        "The function receives a head node. Return the cycle entry node; the judge displays its index, or -1 if there is no cycle.",
        "Floyd's algorithm finds the entry after slow and fast pointers meet.",
        [("[3,2,0,-4]\n1", "1"), ("[1,2]\n0", "0"), ("[1]\n-1", "-1")],
    ),
    _problem(
        "Merge Two Sorted Lists",
        "merge-two-sorted-lists",
        "easy",
        ["Linked List", "Recursion", "Two Pointers"],
        "The function receives two sorted list heads. Merge them and return the merged head; samples display arrays.",
        "Repeatedly link the smaller current node.",
        [("[1,2,4]\n[1,3,4]", "[1,1,2,3,4,4]"), ("[]\n[]", "[]"), ("[]\n[0]", "[0]")],
    ),
    _problem(
        "Remove Nth Node From End of List",
        "remove-nth-node-from-end-of-list",
        "medium",
        ["Linked List", "Two Pointers"],
        "The function receives head and n. Remove the nth node from the end and return the head.",
        "Keep fast and slow pointers n steps apart using a dummy head.",
        [("[1,2,3,4,5]\n2", "[1,2,3,5]"), ("[1]\n1", "[]"), ("[1,2]\n1", "[1]")],
    ),
    _problem(
        "Swap Nodes in Pairs",
        "swap-nodes-in-pairs",
        "medium",
        ["Linked List", "Recursion"],
        "The function receives the list head. Swap every adjacent pair and return the head; samples display arrays.",
        "Process two nodes at a time and leave an odd tail unchanged.",
        [("[1,2,3,4]", "[2,1,4,3]"), ("[]", "[]"), ("[1]", "[1]")],
    ),
    _problem(
        "Reverse Nodes in k-Group",
        "reverse-nodes-in-k-group",
        "hard",
        ["Linked List", "Recursion"],
        "The function receives head and k. Reverse every complete group of k nodes and return the head.",
        "Only reverse blocks whose length is exactly k.",
        [("[1,2,3,4,5]\n2", "[2,1,4,3,5]"), ("[1,2,3,4,5]\n3", "[3,2,1,4,5]"), ("[1,2]\n3", "[1,2]")],
    ),
    _problem(
        "Copy List with Random Pointer",
        "copy-list-with-random-pointer",
        "medium",
        ["Linked List", "Hash Table"],
        "The function receives a random-list head. Samples use [value, random_index] pairs; return the deep-copy head.",
        "Clone nodes first, then wire next and random references by index.",
        [
            ("[[7,null],[13,0],[11,4],[10,2],[1,0]]", "[[7,null],[13,0],[11,4],[10,2],[1,0]]"),
            ("[[1,1],[2,1]]", "[[1,1],[2,1]]"),
            ("[]", "[]"),
        ],
    ),
    _problem(
        "Sort List",
        "sort-list",
        "medium",
        ["Linked List", "Two Pointers", "Sorting", "Merge Sort"],
        "The function receives the list head. Sort nodes in ascending order and return the head; samples display arrays.",
        "Merge sort fits linked lists well.",
        [("[4,2,1,3]", "[1,2,3,4]"), ("[-1,5,3,4,0]", "[-1,0,3,4,5]"), ("[]", "[]")],
    ),
    _problem(
        "Merge k Sorted Lists",
        "merge-k-sorted-lists",
        "hard",
        ["Linked List", "Heap", "Divide and Conquer"],
        "The function receives sorted list heads. Merge all lists and return the merged head; samples use arrays.",
        "Use a min-heap or repeated pairwise merge.",
        [
            ("[[1,4,5],[1,3,4],[2,6]]", "[1,1,2,3,4,4,5,6]"),
            ("[]", "[]"),
            ("[[]]", "[]"),
        ],
    ),
    _problem(
        "LRU Cache",
        "lru-cache",
        "medium",
        ["Hash Table", "Linked List", "Design"],
        "Simulate an LRU cache. Input has operations and argument arrays; output null for writes and values for gets.",
        "Combine a hash table with recency order.",
        [
            ('["LRUCache","put","put","get","put","get","put","get","get","get"]\n[[2],[1,1],[2,2],[1],[3,3],[2],[4,4],[1],[3],[4]]', "[null,null,null,1,null,-1,null,-1,3,4]"),
            ('["LRUCache","put","get"]\n[[1],[2,1],[2]]', "[null,null,1]"),
            ('["LRUCache","put","put","get"]\n[[1],[1,1],[2,2],[1]]', "[null,null,null,-1]"),
        ],
        time_limit=2000,
    ),
    _problem(
        "Binary Tree Inorder Traversal",
        "binary-tree-inorder-traversal",
        "easy",
        ["Stack", "Tree", "Depth-First Search", "Binary Tree"],
        "The function receives root. Samples use a level-order array with nulls; return its inorder traversal.",
        "Traverse left subtree, node, then right subtree.",
        [("[1,null,2,3]", "[1,3,2]"), ("[]", "[]"), ("[1]", "[1]")],
    ),
    _problem(
        "Maximum Depth of Binary Tree",
        "maximum-depth-of-binary-tree",
        "easy",
        ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
        "The function receives root. Samples use a level-order array with nulls; return its maximum depth.",
        "Depth is one plus the larger child depth.",
        [("[3,9,20,null,null,15,7]", "3"), ("[1,null,2]", "2"), ("[]", "0")],
    ),
    _problem(
        "Invert Binary Tree",
        "invert-binary-tree",
        "easy",
        ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
        "The function receives root. Swap every left and right child and return root; samples display level order.",
        "Invert children recursively or with a queue.",
        [
            ("[4,2,7,1,3,6,9]", "[4,7,2,9,6,3,1]"),
            ("[2,1,3]", "[2,3,1]"),
            ("[]", "[]"),
        ],
    ),
    _problem(
        "Symmetric Tree",
        "symmetric-tree",
        "easy",
        ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
        "The function receives root. Return whether it mirrors itself around the root.",
        "Compare the left subtree with the right subtree in mirrored order.",
        [("[1,2,2,3,4,4,3]", "true"), ("[1,2,2,null,3,null,3]", "false"), ("[]", "true")],
    ),
    _problem(
        "Diameter of Binary Tree",
        "diameter-of-binary-tree",
        "easy",
        ["Tree", "Depth-First Search", "Binary Tree"],
        "The function receives root. Return the largest number of edges on any path.",
        "Each node can be the highest point of a path using left depth plus right depth.",
        [("[1,2,3,4,5]", "3"), ("[1,2]", "1"), ("[]", "0")],
    ),
    _problem(
        "Binary Tree Level Order Traversal",
        "binary-tree-level-order-traversal",
        "medium",
        ["Tree", "Breadth-First Search", "Binary Tree"],
        "The function receives root. Return values grouped by depth.",
        "Breadth-first traversal naturally processes one level at a time.",
        [("[3,9,20,null,null,15,7]", "[[3],[9,20],[15,7]]"), ("[1]", "[[1]]"), ("[]", "[]")],
    ),
    _problem(
        "Convert Sorted Array to Binary Search Tree",
        "convert-sorted-array-to-binary-search-tree",
        "easy",
        ["Array", "Divide and Conquer", "Tree", "Binary Search Tree"],
        "Build and return the root of a height-balanced BST by choosing the lower middle value for each range; samples display level order.",
        "Recursive divide-and-conquer keeps both sides balanced.",
        [
            ("[-10,-3,0,5,9]", "[0,-10,5,null,-3,null,9]"),
            ("[1,3]", "[1,null,3]"),
            ("[]", "[]"),
        ],
    ),
    _problem(
        "Validate Binary Search Tree",
        "validate-binary-search-tree",
        "medium",
        ["Tree", "Depth-First Search", "Binary Search Tree", "Binary Tree"],
        "The function receives root. Return whether every node satisfies strict BST bounds.",
        "Carry a lower and upper bound during DFS.",
        [("[2,1,3]", "true"), ("[5,1,4,null,null,3,6]", "false"), ("[2,2,2]", "false")],
    ),
    _problem(
        "Kth Smallest Element in a BST",
        "kth-smallest-element-in-a-bst",
        "medium",
        ["Tree", "Depth-First Search", "Binary Search Tree", "Binary Tree"],
        "The function receives BST root and k. Return the kth smallest value.",
        "Inorder traversal of a BST is sorted.",
        [("[3,1,4,null,2]\n1", "1"), ("[5,3,6,2,4,null,null,1]\n3", "3"), ("[2,1,3]\n2", "2")],
    ),
    _problem(
        "Binary Tree Right Side View",
        "binary-tree-right-side-view",
        "medium",
        ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
        "The function receives root. Return the value visible from the right at each depth.",
        "During BFS, take the last non-null node of every level.",
        [("[1,2,3,null,5,null,4]", "[1,3,4]"), ("[1,null,3]", "[1,3]"), ("[]", "[]")],
    ),
    _problem(
        "Flatten Binary Tree to Linked List",
        "flatten-binary-tree-to-linked-list",
        "medium",
        ["Linked List", "Stack", "Tree", "Depth-First Search", "Binary Tree"],
        "The function receives root and flattens it in place. The judge displays preorder values of the flattened right chain.",
        "The flattened list follows preorder traversal.",
        [("[1,2,5,3,4,null,6]", "[1,2,3,4,5,6]"), ("[]", "[]"), ("[0]", "[0]")],
    ),
    _problem(
        "Construct Binary Tree from Preorder and Inorder Traversal",
        "construct-binary-tree-from-preorder-and-inorder-traversal",
        "medium",
        ["Array", "Hash Table", "Divide and Conquer", "Tree", "Binary Tree"],
        "Given preorder and inorder traversals with distinct values, reconstruct the tree and return root; samples display level order.",
        "The first preorder value is the root; split inorder around it.",
        [("[3,9,20,15,7]\n[9,3,15,20,7]", "[3,9,20,null,null,15,7]"), ("[-1]\n[-1]", "[-1]"), ("[1,2]\n[2,1]", "[1,2]")],
    ),
    _problem(
        "Path Sum III",
        "path-sum-iii",
        "medium",
        ["Tree", "Depth-First Search", "Prefix Sum", "Binary Tree"],
        "The function receives root and targetSum. Count downward paths whose values sum to target.",
        "Use prefix sums along the current root-to-node path.",
        [
            ("[10,5,-3,3,2,null,11,3,-2,null,1]\n8", "3"),
            ("[5,4,8,11,null,13,4,7,2,null,null,5,1]\n22", "3"),
            ("[]\n0", "0"),
        ],
    ),
    _problem(
        "Lowest Common Ancestor of a Binary Tree",
        "lowest-common-ancestor-of-a-binary-tree",
        "medium",
        ["Tree", "Depth-First Search", "Binary Tree"],
        "The function receives root plus nodes p and q. Return their lowest common ancestor; samples display its value.",
        "If p and q are found in different subtrees of a node, that node is the answer.",
        [("[3,5,1,6,2,0,8,null,null,7,4]\n5\n1", "3"), ("[3,5,1,6,2,0,8,null,null,7,4]\n5\n4", "5"), ("[1,2]\n1\n2", "1")],
    ),
    _problem(
        "Binary Tree Maximum Path Sum",
        "binary-tree-maximum-path-sum",
        "hard",
        ["Dynamic Programming", "Tree", "Depth-First Search", "Binary Tree"],
        "The function receives root. Return the maximum sum of any non-empty path.",
        "At each node, keep the best one-side gain and update the best split path.",
        [("[1,2,3]", "6"), ("[-10,9,20,null,null,15,7]", "42"), ("[-3]", "-3")],
    ),
    _problem(
        "Number of Islands",
        "number-of-islands",
        "medium",
        ["Array", "Depth-First Search", "Breadth-First Search", "Matrix"],
        "Given a grid of '1' land and '0' water strings, count connected islands using four directions.",
        "Flood-fill each unvisited land cell.",
        [
            ('[["1","1","1","1","0"],["1","1","0","1","0"],["1","1","0","0","0"],["0","0","0","0","0"]]', "1"),
            ('[["1","1","0","0","0"],["1","1","0","0","0"],["0","0","1","0","0"],["0","0","0","1","1"]]', "3"),
            ('[["0"]]', "0"),
        ],
    ),
    _problem(
        "Rotting Oranges",
        "rotting-oranges",
        "medium",
        ["Array", "Breadth-First Search", "Matrix"],
        "In each minute, rotten oranges rot adjacent fresh oranges. Return minutes until no fresh orange remains, or -1.",
        "Run multi-source BFS from initially rotten cells.",
        [("[[2,1,1],[1,1,0],[0,1,1]]", "4"), ("[[2,1,1],[0,1,1],[1,0,1]]", "-1"), ("[[0,2]]", "0")],
    ),
    _problem(
        "Course Schedule",
        "course-schedule",
        "medium",
        ["Depth-First Search", "Breadth-First Search", "Graph", "Topological Sort"],
        "Given course count and prerequisite pairs [course, prerequisite], return whether all courses can be completed.",
        "A topological ordering exists only when the directed graph has no cycle.",
        [("2\n[[1,0]]", "true"), ("2\n[[1,0],[0,1]]", "false"), ("3\n[[1,0],[2,1]]", "true")],
    ),
    _problem(
        "Implement Trie (Prefix Tree)",
        "implement-trie-prefix-tree",
        "medium",
        ["Hash Table", "String", "Design", "Trie"],
        "Simulate Trie operations insert, search, and startsWith. Output null for inserts and booleans for queries.",
        "Each node maps characters to child nodes and can mark the end of a word.",
        [
            ('["Trie","insert","search","search","startsWith","insert","search"]\n[[],["apple"],["apple"],["app"],["app"],["app"],["app"]]', "[null,null,true,false,true,null,true]"),
            ('["Trie","insert","startsWith","search"]\n[[],["dog"],["do"],["dog"]]', "[null,null,true,true]"),
            ('["Trie","search"]\n[[],["a"]]', "[null,false]"),
        ],
    ),
    _problem(
        "Permutations",
        "permutations",
        "medium",
        ["Array", "Backtracking"],
        "Return every permutation of distinct integers in lexicographic order.",
        "Track which values are already used in the current path.",
        [
            ("[1,2,3]", "[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]"),
            ("[0,1]", "[[0,1],[1,0]]"),
            ("[1]", "[[1]]"),
        ],
        time_limit=2000,
    ),
    _problem(
        "Subsets",
        "subsets",
        "medium",
        ["Array", "Backtracking", "Bit Manipulation"],
        "Return all subsets of distinct integers, with each subset and the outer list in lexicographic order.",
        "At each index, either include the current value or skip it.",
        [("[1,2,3]", "[[],[1],[1,2],[1,2,3],[1,3],[2],[2,3],[3]]"), ("[0]", "[[],[0]]"), ("[1,2]", "[[],[1],[1,2],[2]]")],
    ),
    _problem(
        "Letter Combinations of a Phone Number",
        "letter-combinations-of-a-phone-number",
        "medium",
        ["String", "Backtracking"],
        "Map digits 2 through 9 to phone keypad letters and output every possible string in keypad order.",
        "Build combinations one digit at a time with DFS.",
        [
            ("23", '["ad","ae","af","bd","be","bf","cd","ce","cf"]'),
            ("", "[]"),
            ("7", '["p","q","r","s"]'),
        ],
    ),
    _problem(
        "Combination Sum",
        "combination-sum",
        "medium",
        ["Array", "Backtracking"],
        "Return all unique nondecreasing combinations that sum to target; each candidate may be reused.",
        "DFS from a start index so combinations remain nondecreasing.",
        [
            ("[2,3,6,7]\n7", "[[2,2,3],[7]]"),
            ("[2,3,5]\n8", "[[2,2,2,2],[2,3,3],[3,5]]"),
            ("[2]\n1", "[]"),
        ],
    ),
    _problem(
        "Generate Parentheses",
        "generate-parentheses",
        "medium",
        ["String", "Backtracking"],
        "Generate every balanced parentheses string containing n pairs, in DFS order with '(' before ')'.",
        "Add '(' while any remain, and add ')' only when it keeps the prefix valid.",
        [
            ("3", '["((()))","(()())","(())()","()(())","()()()"]'),
            ("1", '["()"]'),
            ("2", '["(())","()()"]'),
        ],
    ),
    _problem(
        "Word Search",
        "word-search",
        "medium",
        ["Array", "Backtracking", "Matrix"],
        "Given a board of characters and a word, return whether the word can be formed by adjacent cells without reusing a cell.",
        "Backtrack from cells matching the next character.",
        [
            ('[["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]]\nABCCED', "true"),
            ('[["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]]\nSEE', "true"),
            ('[["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]]\nABCB', "false"),
        ],
    ),
    _problem(
        "Palindrome Partitioning",
        "palindrome-partitioning",
        "medium",
        ["String", "Dynamic Programming", "Backtracking"],
        "Partition a string so every segment is a palindrome. Return partitions in DFS order.",
        "Precompute palindrome ranges, then backtrack through valid cuts.",
        [("aab", '[["a","a","b"],["aa","b"]]'), ("a", '[["a"]]'), ("efe", '[["e","f","e"],["efe"]]')],
    ),
    _problem(
        "N-Queens",
        "n-queens",
        "hard",
        ["Array", "Backtracking"],
        "Place n queens on an n by n board so none attack each other. Return board strings in row-major DFS order.",
        "Track used columns and diagonals while placing one queen per row.",
        [
            ("4", '[[".Q..","...Q","Q...","..Q."],["..Q.","Q...","...Q",".Q.."]]'),
            ("1", '[["Q"]]'),
            ("2", "[]"),
        ],
        time_limit=2000,
    ),
    _problem(
        "Search Insert Position",
        "search-insert-position",
        "easy",
        ["Array", "Binary Search"],
        "Given a sorted array and target, return its index or the insertion index that keeps the array sorted.",
        "Use lower_bound binary search.",
        [("[1,3,5,6]\n5", "2"), ("[1,3,5,6]\n2", "1"), ("[1,3,5,6]\n7", "4")],
    ),
    _problem(
        "Search a 2D Matrix",
        "search-a-2d-matrix",
        "medium",
        ["Array", "Binary Search", "Matrix"],
        "Rows are sorted and each row starts after the previous row ends. Return whether target exists.",
        "Treat the matrix as one flattened sorted array.",
        [
            ("[[1,3,5,7],[10,11,16,20],[23,30,34,60]]\n3", "true"),
            ("[[1,3,5,7],[10,11,16,20],[23,30,34,60]]\n13", "false"),
            ("[[1]]\n1", "true"),
        ],
    ),
    _problem(
        "Find First and Last Position of Element in Sorted Array",
        "find-first-and-last-position-of-element-in-sorted-array",
        "medium",
        ["Array", "Binary Search"],
        "Return the first and last indices of a target in a sorted array, or [-1,-1].",
        "Run lower-bound searches for target and the first value greater than target.",
        [("[5,7,7,8,8,10]\n8", "[3,4]"), ("[5,7,7,8,8,10]\n6", "[-1,-1]"), ("[]\n0", "[-1,-1]")],
    ),
    _problem(
        "Search in Rotated Sorted Array",
        "search-in-rotated-sorted-array",
        "medium",
        ["Array", "Binary Search"],
        "Find target in a distinct sorted array that has been rotated, or return -1.",
        "At least one side of every binary-search split is sorted.",
        [("[4,5,6,7,0,1,2]\n0", "4"), ("[4,5,6,7,0,1,2]\n3", "-1"), ("[1]\n0", "-1")],
    ),
    _problem(
        "Find Minimum in Rotated Sorted Array",
        "find-minimum-in-rotated-sorted-array",
        "medium",
        ["Array", "Binary Search"],
        "Return the minimum value in a rotated sorted array with distinct values.",
        "Compare the middle value with the right boundary to discard a sorted half.",
        [("[3,4,5,1,2]", "1"), ("[4,5,6,7,0,1,2]", "0"), ("[11,13,15,17]", "11")],
    ),
    _problem(
        "Median of Two Sorted Arrays",
        "median-of-two-sorted-arrays",
        "hard",
        ["Array", "Binary Search", "Divide and Conquer"],
        "Given two sorted integer arrays, return the median of their combined sorted sequence.",
        "Binary search a partition where every left-side value is no larger than every right-side value.",
        [("[1,3]\n[2]", "2.0"), ("[1,2]\n[3,4]", "2.5"), ("[]\n[1]", "1.0")],
        time_limit=2000,
    ),
    _problem(
        "Min Stack",
        "min-stack",
        "medium",
        ["Stack", "Design"],
        "Simulate MinStack operations. Output null for mutations and values for top/getMin.",
        "Store each pushed value with the minimum value at that stack depth.",
        [
            ('["MinStack","push","push","push","getMin","pop","top","getMin"]\n[[],[-2],[0],[-3],[],[],[],[]]', "[null,null,null,null,-3,null,0,-2]"),
            ('["MinStack","push","top","getMin"]\n[[],[1],[],[]]', "[null,null,1,1]"),
            ('["MinStack","push","push","getMin"]\n[[],[2],[1],[]]', "[null,null,null,1]"),
        ],
    ),
    _problem(
        "Decode String",
        "decode-string",
        "medium",
        ["String", "Stack", "Recursion"],
        "Decode strings with k[encoded] repetition syntax.",
        "Use a stack to save the previous prefix and repeat count at each '['.",
        [("3[a]2[bc]", "aaabcbc"), ("3[a2[c]]", "accaccacc"), ("2[abc]3[cd]ef", "abcabccdcdcdef")],
    ),
    _problem(
        "Daily Temperatures",
        "daily-temperatures",
        "medium",
        ["Array", "Stack", "Monotonic Stack"],
        "For each day, return how many days must pass before a warmer temperature occurs, or 0.",
        "Keep unresolved day indexes in decreasing temperature order.",
        [
            ("[73,74,75,71,69,72,76,73]", "[1,1,4,2,1,1,0,0]"),
            ("[30,40,50,60]", "[1,1,1,0]"),
            ("[30,60,90]", "[1,1,0]"),
        ],
    ),
    _problem(
        "Largest Rectangle in Histogram",
        "largest-rectangle-in-histogram",
        "hard",
        ["Array", "Stack", "Monotonic Stack"],
        "Given histogram bar heights, return the largest rectangle area.",
        "A monotonic stack finds the nearest smaller bar on both sides.",
        [("[2,1,5,6,2,3]", "10"), ("[2,4]", "4"), ("[1,1]", "2")],
    ),
    _problem(
        "Kth Largest Element in an Array",
        "kth-largest-element-in-an-array",
        "medium",
        ["Array", "Divide and Conquer", "Sorting", "Heap"],
        "Return the kth largest value in the array.",
        "A size-k min-heap or quickselect avoids full sorting.",
        [("[3,2,1,5,6,4]\n2", "5"), ("[3,2,3,1,2,4,5,5,6]\n4", "4"), ("[1]\n1", "1")],
    ),
    _problem(
        "Top K Frequent Elements",
        "top-k-frequent-elements",
        "medium",
        ["Array", "Hash Table", "Heap", "Bucket Sort"],
        "Return the k most frequent values, ordered by descending frequency then ascending value.",
        "Count values first, then sort or bucket by frequency.",
        [("[1,1,1,2,2,3]\n2", "[1,2]"), ("[1]\n1", "[1]"), ("[4,4,6,6,6,7]\n2", "[6,4]")],
    ),
    _problem(
        "Find Median from Data Stream",
        "find-median-from-data-stream",
        "hard",
        ["Two Heaps", "Design", "Heap", "Data Stream"],
        "Simulate MedianFinder operations. Output null for adds and medians as numbers.",
        "Use one max-heap for the lower half and one min-heap for the upper half.",
        [
            ('["MedianFinder","addNum","addNum","findMedian","addNum","findMedian"]\n[[],[1],[2],[],[3],[]]', "[null,null,null,1.5,null,2.0]"),
            ('["MedianFinder","addNum","findMedian"]\n[[],[5],[]]', "[null,null,5.0]"),
            ('["MedianFinder","addNum","addNum","findMedian"]\n[[],[2],[1],[]]', "[null,null,null,1.5]"),
        ],
    ),
    _problem(
        "Best Time to Buy and Sell Stock",
        "best-time-to-buy-and-sell-stock",
        "easy",
        ["Array", "Dynamic Programming"],
        "Given daily prices, return the maximum profit from one buy followed by one sell.",
        "Track the lowest price seen before the current day.",
        [("[7,1,5,3,6,4]", "5"), ("[7,6,4,3,1]", "0"), ("[2,4,1]", "2")],
    ),
    _problem(
        "Jump Game",
        "jump-game",
        "medium",
        ["Array", "Greedy", "Dynamic Programming"],
        "Each value is the maximum jump length from that index. Return whether the final index is reachable.",
        "Track the farthest reachable index while scanning.",
        [("[2,3,1,1,4]", "true"), ("[3,2,1,0,4]", "false"), ("[0]", "true")],
    ),
    _problem(
        "Jump Game II",
        "jump-game-ii",
        "medium",
        ["Array", "Greedy", "Dynamic Programming"],
        "Return the minimum number of jumps needed to reach the final index.",
        "When the scan reaches the end of the current jump range, commit one jump.",
        [("[2,3,1,1,4]", "2"), ("[2,3,0,1,4]", "2"), ("[0]", "0")],
    ),
    _problem(
        "Partition Labels",
        "partition-labels",
        "medium",
        ["String", "Greedy", "Hash Table", "Two Pointers"],
        "Split a string into as many parts as possible so each letter appears in at most one part. Return part lengths.",
        "A partition ends when the current index reaches the farthest last occurrence of any included character.",
        [("ababcbacadefegdehijhklij", "[9,7,8]"), ("eccbbbbdec", "[10]"), ("caedbdedda", "[1,9]")],
    ),
    _problem(
        "Pascal's Triangle",
        "pascals-triangle",
        "easy",
        ["Array", "Dynamic Programming"],
        "Return the first numRows of Pascal's triangle.",
        "Each interior value is the sum of two values from the previous row.",
        [("5", "[[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]]"), ("1", "[[1]]"), ("2", "[[1],[1,1]]")],
    ),
    _problem(
        "House Robber",
        "house-robber",
        "medium",
        ["Array", "Dynamic Programming"],
        "Return the maximum amount that can be robbed without taking money from adjacent houses.",
        "For each house, choose between taking it plus the best two houses back or skipping it.",
        [("[1,2,3,1]", "4"), ("[2,7,9,3,1]", "12"), ("[2,1,1,2]", "4")],
    ),
    _problem(
        "Perfect Squares",
        "perfect-squares",
        "medium",
        ["Math", "Dynamic Programming", "Breadth-First Search"],
        "Return the fewest number of perfect square numbers that sum to n.",
        "Run coin-change DP with square numbers as coins.",
        [("12", "3"), ("13", "2"), ("1", "1")],
    ),
    _problem(
        "Coin Change",
        "coin-change",
        "medium",
        ["Array", "Dynamic Programming", "Breadth-First Search"],
        "Given coin denominations and an amount, return the fewest coins needed or -1 if impossible.",
        "Classic unbounded knapsack over amounts.",
        [("[1,2,5]\n11", "3"), ("[2]\n3", "-1"), ("[1]\n0", "0")],
    ),
    _problem(
        "Word Break",
        "word-break",
        "medium",
        ["Hash Table", "String", "Dynamic Programming", "Trie"],
        "Return whether s can be segmented into dictionary words.",
        "Let dp[i] mean the prefix ending at i can be segmented.",
        [('leetcode\n["leet","code"]', "true"), ('applepenapple\n["apple","pen"]', "true"), ('catsandog\n["cats","dog","sand","and","cat"]', "false")],
    ),
    _problem(
        "Longest Increasing Subsequence",
        "longest-increasing-subsequence",
        "medium",
        ["Array", "Dynamic Programming", "Binary Search"],
        "Given an integer array, return the length of the longest strictly increasing subsequence.",
        "Maintain the smallest possible tail for each subsequence length.",
        [("[10,9,2,5,3,7,101,18]", "4"), ("[0,1,0,3,2,3]", "4"), ("[7,7,7,7,7,7,7]", "1")],
    ),
    _problem(
        "Maximum Product Subarray",
        "maximum-product-subarray",
        "medium",
        ["Array", "Dynamic Programming"],
        "Return the largest product of any non-empty contiguous subarray.",
        "Track both the maximum and minimum product ending at the current index.",
        [("[2,3,-2,4]", "6"), ("[-2,0,-1]", "0"), ("[-2,3,-4]", "24")],
    ),
    _problem(
        "Partition Equal Subset Sum",
        "partition-equal-subset-sum",
        "medium",
        ["Array", "Dynamic Programming", "Knapsack"],
        "Return whether the array can be split into two subsets with equal sum.",
        "The target is half the total sum; solve subset sum.",
        [("[1,5,11,5]", "true"), ("[1,2,3,5]", "false"), ("[2,2,3,5]", "false")],
    ),
    _problem(
        "Longest Valid Parentheses",
        "longest-valid-parentheses",
        "hard",
        ["String", "Stack", "Dynamic Programming"],
        "Given a parentheses string, return the length of the longest contiguous valid parentheses substring.",
        "Use a stack of unmatched indexes and a base position after invalid closes.",
        [("(()", "2"), (")()())", "4"), ("()(())", "6")],
    ),
    _problem(
        "Unique Paths",
        "unique-paths",
        "medium",
        ["Math", "Dynamic Programming", "Combinatorics"],
        "Count paths from the top-left to bottom-right of an m by n grid using only right and down moves.",
        "Each cell collects paths from above and from the left.",
        [("3\n7", "28"), ("3\n2", "3"), ("1\n10", "1")],
    ),
    _problem(
        "Minimum Path Sum",
        "minimum-path-sum",
        "medium",
        ["Array", "Dynamic Programming", "Matrix"],
        "Find the minimum sum along a path from top-left to bottom-right, moving only right or down.",
        "Each cell depends on the cheaper of the top and left predecessor costs.",
        [("[[1,3,1],[1,5,1],[4,2,1]]", "7"), ("[[1,2,3],[4,5,6]]", "12"), ("[[5]]", "5")],
    ),
    _problem(
        "Longest Palindromic Substring",
        "longest-palindromic-substring",
        "medium",
        ["String", "Dynamic Programming", "Two Pointers"],
        "Return the longest palindromic substring. If tied, return the earliest one.",
        "Expand around every odd and even center.",
        [("babad", "bab"), ("cbbd", "bb"), ("forgeeksskeegfor", "geeksskeeg")],
    ),
    _problem(
        "Longest Common Subsequence",
        "longest-common-subsequence",
        "medium",
        ["String", "Dynamic Programming"],
        "Given two strings, return the length of their longest common subsequence.",
        "Compare prefixes and keep the better result after matching or skipping a character.",
        [("abcde\nace", "3"), ("abc\nabc", "3"), ("abc\ndef", "0")],
    ),
    _problem(
        "Edit Distance",
        "edit-distance",
        "hard",
        ["String", "Dynamic Programming"],
        "Return the minimum number of insertions, deletions, and replacements needed to transform one word into another.",
        "For differing last characters, choose the cheapest replace, delete, or insert transition.",
        [("horse\nros", "3"), ("intention\nexecution", "5"), ("abc\nabc", "0")],
        time_limit=2000,
    ),
    _problem(
        "Single Number",
        "single-number",
        "easy",
        ["Array", "Bit Manipulation"],
        "Every value appears twice except one value. Return the value that appears once.",
        "XOR cancels equal pairs.",
        [("[2,2,1]", "1"), ("[4,1,2,1,2]", "4"), ("[1]", "1")],
    ),
    _problem(
        "Majority Element",
        "majority-element",
        "easy",
        ["Array", "Counting"],
        "Return the value that appears more than half the time.",
        "Boyer-Moore voting cancels different values.",
        [("[3,2,3]", "3"), ("[2,2,1,1,1,2,2]", "2"), ("[1,1,1,2,3]", "1")],
    ),
    _problem(
        "Sort Colors",
        "sort-colors",
        "medium",
        ["Array", "Two Pointers", "Sorting"],
        "Sort an array containing only 0, 1, and 2.",
        "Dutch-national-flag partitioning keeps three value regions.",
        [("[2,0,2,1,1,0]", "[0,0,1,1,2,2]"), ("[2,0,1]", "[0,1,2]"), ("[0]", "[0]")],
    ),
    _problem(
        "Next Permutation",
        "next-permutation",
        "medium",
        ["Array", "Two Pointers"],
        "Return the next lexicographic permutation, or the smallest permutation if none is larger.",
        "Find the rightmost ascent, swap with the next larger suffix value, then reverse the suffix.",
        [("[1,2,3]", "[1,3,2]"), ("[3,2,1]", "[1,2,3]"), ("[1,1,5]", "[1,5,1]")],
    ),
    _problem(
        "Find the Duplicate Number",
        "find-the-duplicate-number",
        "medium",
        ["Array", "Two Pointers", "Binary Search"],
        "An array of length n + 1 contains values from 1 to n with one repeated value. Return the repeated value.",
        "Treat values as next pointers and find the cycle entrance.",
        [("[1,3,4,2,2]", "2"), ("[3,1,3,4,2]", "3"), ("[1,1]", "1")],
    ),
]
